acteng/atip

.github/workflows/web.yml, .gitignore, route-snapper/Cargo.lock, route-snapper/Cargo.toml, route-snapper/lib.js, route-snapper/src/lib.rs, routes.html, serve_locally.sh
Instead of loading a fixed A/B Street map file for the route snapper, now we dynamically fetch a file. Its contents are a new binary-encoded format, created in https://github.com/acteng/abstreet-to-atip/blob/main/src/route_snapper.rs. This just has the geometry and graph structure needed to do route snapping, so it's way smaller than the abst map.
This gets things working for a few more areas. The files are hosted in my abst S3 bucket right now, and manually created/uploaded with scripts in the other repo. I need to do more work to clean up that process and run it for all authorities.
Still loads of cleanup needed. I want to make a separate git repo, just for this new route snapping plugin. It has nothing to do with ATIP, other than being needed by it. :)
=> Use a custom file for route snapper, per authority

route-snapper/lib.js, route-snapper/src/lib.rs
#43 
Hold down shift to draw freehand.
https://user-images.githubusercontent.com/1664407/205376229-d28465dd-0047-4e06-bbfb-36ee800b1e99.mp4
The interaction needs more work, but a solid step forward. Biggest next things to figure out:
1) Drag freehand points too
2) Maybe auto-snap after ending a freehand segment. Right now you have to add an extra point that snaps to an intersection before you can continue the route
3) Display context-sensitive instructions saying things like "hold shift"
=> Make the route snapper be able to draw free-form segments too

components/BoundaryLayer.svelte, package-lock.json, package.json
Previously:
This makes it much easier to distinguish the inside and outside of the study area, and should make it clear why the route tool stops at the boundary. But it might discourage schemes that cross boundaries, especially because the mask color is so dark. Should we do this or not?
=> Fade out everything outside of the boundary

components/EntireScheme.svelte
This PR attempts to start to address #65 
In particular including some validation to check an uploaded geojson is one that was generated from the ATIP platform.
Summary of changes:
- Adding an origin field to generated geojson that specifies `atip-v1`
- Adding a validation step in `loadFile` that checks for this origin field
Outstanding tasks:
=> Defining origin of generated geojson files

package-lock.json, package.json
Before:
https://user-images.githubusercontent.com/1664407/216993545-361ffb16-237a-4559-b761-432574e33654.mp4
After:
https://user-images.githubusercontent.com/1664407/216993568-aa367f9b-2af1-489e-93f7-c9893b861679.mp4
Note the polygon tool is shaded when active on the 2nd. The other changes in https://github.com/mapbox/mapbox-gl-draw/blob/main/CHANGELOG.md don't affect us.
=> Update mapbox-gl-draw, fixing the active styling on the controls

package-lock.json
and new routes drawn will have a length_meters property
https://user-images.githubusercontent.com/1664407/218472870-0d2a75b0-2b1a-4075-a830-ced88b656b1a.mp4
For convenience, you can play with the new option at https://dabreegster.github.io/route_snapper/ too. Note this change also starts adding a `length_meters` property to the GeoJSON. Files people submit may or may not contain this field, since people might've used an old version of ATIP. We can easily "backfill" this on the analysis side if needed.
=> Update route-snapper. Users can now prevent routes from doubling back,

components/EntireScheme.svelte
This PR removes checkOrigin based input validation and moves foreign member creation ("authority" and "origin") to the exportGeojson function.
It aims to address issues described in #78 and #72 
Tested instances:
✅ Current prod geojson - [Warwickshire-all-fields.txt](https://github.com/acteng/atip/files/10742576/Warwickshire-all-fields.txt)
✅ Only scheme_name (generated from a cleared map and redraw) - [Warwickshire_A47.Hinckley.Road-just-scheme-name.txt](https://github.com/acteng/atip/files/10742578/Warwickshire_A47.Hinckley.Road-just-scheme-name.txt)
✅ No foreign members - [Warwickshire-no-foreign-members.txt](https://github.com/acteng/atip/files/10742575/Warwickshire-no-foreign-members.txt)
=> Remove Input validation against foreign members

tests/atip-map-interact.spec.js, tests/hello-atip.spec.js, tests/test-utils.js
This PR improves upon the previous PR introducing playwright.
In that PR we randomly allocated a port number for tests using a utility function. A nicer way to set random port numbers is to specify port 0 and allow the OS to randomly assign from an available port for each test.
=> random port assignment for tests using port 0

components/Map.svelte
I've been copying around the API key from MapLibre examples, but this morning on conference wifi, I got 403's for it. Seemingly not an issue off of conference wifi, but this is a ticking time-bomb anyway. In the short term, signing up for a free account was super easy, and the request quota should be more than enough. We can keep considering various other options for hosting long-term, but this moves us forward a bit.
As an aside, MapTiler has a v2 of the streets style. I kept the same one so far, but here's a comparison. Current:
v2:
=> Switch to our own MapTiler free account. #59

components/Map.svelte
Small but annoying thing: on the current site, hold control and click around to make the camera 3D. It's hard to reset to top-down. The compass control we already have in the corner will fix rotation, but not pitch. This fixes that to always reset to neutral.
https://user-images.githubusercontent.com/1664407/227202181-5ecee96d-1157-44dd-8aef-fc843bc283bc.mp4
=> Let people reset 3D camera

components/BoundaryLayer.svelte, components/DrawControls.svelte, components/EditingLayer.svelte, components/HoverLayer.svelte, maplibre_helpers.js
Vite does hot-module reloading (HMR), meaning when you edit code, just the necessary Svelte components get reloaded without the whole page refreshing. It's incredibly handy to tune CSS or map drawing styles things and instantly see feedback. But today, if you edit the code in many ATIP components, the page breaks completely.
This PR fixes most of the cases involving sources and layers on the map. MapLibre doesn't let you add a source or layer with a duplicate ID. We could solve this in a few ways:
- Writing an `onDestroy` for all relevant components, and carefully removing things in the correct order. (Layers have to be removed before their source). Boilerplatey, and really easy to get wrong.
- Using Svelte components that wrap Sources and Layers and do the lifetime management properly. …
=> Less clunky developer experience, part 1

components/Form.svelte, stores.js
This is a small tweak that makes navigation/editing easier. If someone picks an intervention, they probably want to actually see the entire form.
Before:
https://user-images.githubusercontent.com/1664407/228212695-c4638fc0-3b63-486a-b7ee-b6450bfce2c4.mp4
After:
https://user-images.githubusercontent.com/1664407/228212718-85059976-8b7d-42b2-9232-24884957f3e4.mp4
=> When we expand a form, scroll to ensure it's visible in the sidebar

components/DrawControls.svelte, components/HoverLayer.svelte, components/InterventionList.svelte, stores.js
As part of #58, I've been trying to detangle all the state we have and determine valid interactions during different drawing/editing modes. This is a smaller refactoring that changes behavior. I believe it makes it nicer and more consistent, but please evaluate the UX of it.
Before, we draw an outline for stuff on the map when you hover in the sidebar, but not when you hover on the map. And when something is being edited, you can partly change the hover state independently:
https://user-images.githubusercontent.com/1664407/229165708-e1037a25-770a-4e19-89d4-0aa48c9bded6.mp4
With this PR, I'm merging the concept of "currently hovered object" to be just one thing -- whether it's from the sidebar or the map. And when something is being edited, you can't change the hover state. …
=> Make hovering more consistent

colors.js, components/draw/InterventionLayer.svelte, components/draw/SplitRouteMode.svelte, components/draw/Toolbox.svelte, package-lock.json, package.json, stores.js
https://user-images.githubusercontent.com/1664407/231227440-89f0468e-7b08-485a-b500-d372046ce3b6.mp4
Here's a new mode to split routes. The intended flow is that users will first sketch the overall route they want, then later optionally fill in more info about different sections of the route. The specific interventions will likely vary based on available width and other factors. This tool helps them refine a long route into shorter ones.
There's one big task left before this PR is ready: when we split a route, we need to update the route-snapper's stored waypoints, so that we can then edit each piece individually.
Some inspiration for other line splitting tools in the mapbox-gl-draw ecosystem: https://github.com/ReyhaneMasumi/mapbox-gl-draw-split-line-mode, …
=> Split routes

README.md, src/lib/draw/AttributeMode.svelte, src/lib/draw/GeometryMode.svelte, src/lib/draw/events.ts, src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/SplitRouteMode.svelte, src/lib/draw/route/route_tool.ts
As the edits near `README` describe, we have to be a bit careful about unregistering any document/map/etc event handlers when a Svelte component gets torn down. Otherwise as you edit a component, every previous version of the callback keeps running! This PR fixes most remaining problems; see comments below for the strategy.
The last big remaining problem is the custom observable pattern used in all the `*tool.ts` classes with `addEventListener`. We need to clean those up too.
=> Manage callbacks better

src/lib/draw/GeometryMode.svelte, src/lib/draw/KeyHandler.svelte, src/lib/draw/point/PointControls.svelte, src/lib/draw/point/PointMode.svelte, src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/PolygonControls.svelte, src/lib/draw/polygon/PolygonMode.svelte, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/SplitRouteMode.svelte, src/lib/draw/route/route_tool.ts
This adds a clickable cancel button to all modes, and lets pressing the escape key also work. #124 
Weird caveat: listening for the escape key only works after clicking on the page. Not sure why.
=> Consistent controls to stop drawing

package-lock.json, package.json, src/lib/draw/GeometryMode.svelte, src/lib/draw/Toolbox.svelte, src/lib/draw/polygon/PolygonMode.svelte, src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/RouteMode.svelte, src/lib/draw/route/route_tool.ts, src/lib/draw/snap_polygon/SnapPolygonControls.svelte, src/lib/draw/snap_polygon/SnapPolygonMode.svelte, src/lib/draw/types.ts
#118
https://user-images.githubusercontent.com/1664407/234880094-2674b4cd-ba4e-4d7c-a2a2-60834e62226a.mp4
For now, the new tool is distinct from the previous freehand polygon tool. In the future, we could try to merge the two, allowing easy freehand points alongside snapping. But for now, it's too tough.
As a note, this was a super quick change to crank out, because TS had my back. I had one or two bugs (forgetting to glue something up) and the compiler told me. I'm very happy with the decision to use it.
=> New polygon snap tool

package.json, src/App.svelte, src/lib/InterventionList.svelte, src/lib/forms/CriticalsForm.svelte, src/schemas/criticals.json, src/schemas/criticals.ts, src/types.ts
This is based on v2.0 of the ATE inspection spreadsheet
Related to https://github.com/acteng/overview/issues/27 -- this isn't a way to automatically discover critical issues, but a schema and UI in ATIP to collect/display the problems.
The UX of a radio button with 15 options and long descriptions is awful:
But I'll merge this and iterate on other designs. Suggestions very welcome.
=> Add a schema for critical issues.

.github/workflows/playwright.yml, .github/workflows/web.yml
See the issue for details. Previously, the most recently run workflow in any branch was overwriting `main`!
=> Fix GH workflows to handle multiple branches properly. #104

package-lock.json, package.json, tests/add-delete-add.spec.ts, tests/add-route.spec.ts
This PR adds some tests for adding route interventions and updated playwright version to get access to [`--ui`](https://playwright.dev/docs/test-ui-mode) mode.
These tests include one test that aims to capture the bug described in #162 and so I expect it to fail checks.
Test code was produced using codegen which is pretty nice.
=> Adding some tests for adding route intervention

index.html, src/lib/About.svelte, src/lib/CollapsibleCard.svelte, src/lib/Legend.svelte, src/lib/draw/polygon/PolygonControls.svelte, src/lib/draw/route/RouteControls.svelte, src/lib/draw/snap_polygon/SnapPolygonControls.svelte
During in-person UX testing with Robin last week, we decided the current legend should be de-emphasized. It'll probably change even more once we work on contextual layers, but for now, I've made it collapsible, starting open by default:
https://github.com/acteng/atip/assets/1664407/c6d2c33c-0ea4-4a16-aa2c-e90119195c75
=> Make the legend collapsible

src/lib/draw/route/SplitRouteMode.svelte, src/lib/forms/FormV1.svelte
From watching UX sessions, two small things jumped out, easy to fix:
The "Auto-fill details" button is too far away from where people type in the name, and its effect is unclear. So move it:
In the split tool, someone was confused by "Click near a route". I just meant the mouse doesn't need to be exactly on the route before it snaps, but that's obvious anyway when trying to use it. So adjust the wording to "Click on a route"
=> Small UX tweaks

src/lib/sidebar/Instructions.svelte
Closes #116. I tried to reduce the level of detail, encouraging people to use each tool's instructions or help button.
Some of the instructions may depend on the schema (eg, planning or criticals). Do we want to customize anything, or give more specific guidance about the level of detail in a scheme we're asking for?
=> Rewrite instructions

src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/route_tool.ts
This came up several times in the UX study -- people expected to double click to end a route. For now, I've made double click always try to finish things -- even if someone double clicks a waypoint somewhere in the middle. Is that reasonable, or should we have different behavior?
Try at https://acteng.github.io/atip/double_click_to_end/scheme.html?authority=Derby
This PR is related to https://github.com/dabreegster/route_snapper/pull/30. We'd have to do this PR regardless; the changes in the other one only affect users of the `lib.js`, which we stopped using a while ago.
=> Double click to finish a route

package-lock.json, package.json, src/lib/BoundaryLayer.svelte, src/lib/draw/HoverLayer.svelte, src/lib/draw/InterventionLayer.svelte, src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/SplitRouteMode.svelte, src/lib/draw/route/route_tool.ts, src/lib/layers/SpeedLimits.svelte, src/maplibre_helpers.ts
Part of #89. Previously, we used one big `overwriteLayer` call, but couldn't specify `LayerSpecification` on one of the parameters without getting some bizarre TS errors. After fighting this for a while, I decided it's more clear to split the function into 3 smaller ones specifically for circles, polygons, and lines. That makes the parameters easier to specify, anyway.
This should be a pure refactoring PR, no behavioral change (that I've spotted!)
=> Refactor code to create layers

src/lib/draw/polygon/PolygonControls.svelte, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/route_tool.ts, src/lib/draw/snap_polygon/SnapPolygonControls.svelte
Robin noticed this bug yesterday. Thanks to OSMUS for advice: https://osmus.slack.com/archives/C01G3D28DAB/p1685016451984109
We have a remaining bug double clicking in the snap polygon tool, but the fix for that needs to happen in the route-snapper repo; I'll do it separately.
=> Double click to finish a freehand polygon

route_info/Cargo.lock, route_info/src/lib.rs, src/lib/forms/RouteInfoLayers.svelte, src/lib/layers/ContextualLayers.svelte, src/lib/layers/LaneDetails.svelte, src/lib/layers/lane_details/IntersectionMarkings.svelte, src/lib/layers/lane_details/IntersectionPolygons.svelte, src/lib/layers/lane_details/LaneMarkings.svelte, src/lib/layers/lane_details/LanePolygons.svelte, src/lib/layers/lane_details/Layer.svelte, src/maplibre_helpers.ts, src/worker.ts
Now that we have osm2streets.org hooked up to ATIP, it's relatively easy for us to attempt something kind of cool: rendering detailed lanes along a route! CC @BudgieInWA. Preview at https://acteng.github.io/atip/layer_lanes/scheme.html?authority=Derby.
https://github.com/acteng/atip/assets/1664407/dbab2d42-beeb-4093-a60b-ab475b88d568
First of all, there are loads of caveats with the rendering. The video above shows a few glaring problems! A big question should be how people will use this; does it solve any concrete problem right now? Is the danger of misinterpretation high and we should work towards this kind of thing eventually, but only add it once it's stabler? My motivation is partly to make osm2streets work even more visible, to drive improvements and feature requests (as a starter …
=> Add a layer to render lane details along a route

src/pages/App.svelte
A simple cutover to the new files. All the magic happens in the browser, because it sees a `content-encoding: gzip` header.
I didn't measure e2e perf differences, but I expect the savings to be pretty good, especially on slower internet, based on the compression ratios for route-info files.
Going to ASAP merge because it's pretty non-controversial
=> Use gzipped route info and snapper files

package-lock.json, package.json, src/lib/draw/GeometryMode.svelte, src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/RouteMode.svelte, src/lib/draw/route/route_tool.ts
See https://github.com/dabreegster/route_snapper/pull/30 for context. I haven't done UX testing with anyone, but I suspect this'll make the default experience much less weird. It's much easier to drag intermediate waypoints this way.
For people who want to change the default, combined with #201 would let them make the setting sticky.
=> By default, don't keep appending points to the end of a route

src/lib/forms/FormV1.svelte
=> Hide the autofill button unless we have a linestring

src/pages/App.svelte
I propose we change how we version the two sets of binary route data files. Previously I've been copying the same data between a dev (for the auto-deployed github version) and prod (for atip.uk), but there's an inherent awkwardness when updating the dev data format in sync with the code change. No reason for that complication; we can just put an arbitrary version number for the data files, and pin the code to that version.
I've used "v2" here for the data file, and don't really care how we increment this later (v2.1, v3, etc) -- as long as the strings are unique and we update the URL here, it'll be fine.
I haven't copied the files in S3 to this new URL directory structure yet; will do so once we agree on the naming of it. And will update abstreet-to-atip scripts too.
=> Use numbered versions for data files

src/lib/common/MapTooltips.svelte, src/pages/BrowseSchemes.svelte
#173 
This now takes `magicfoo.geojson` as input -- the previous input files will _not_ work. And the tooltips are formatted better.
=> Improve scheme browse page

tsconfig.json
In `main` right now, `npm run check` complains:
```
Error: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled. 
import { expect, test, type Page } from "@playwright/test";
import { loadInitialPage, clearExistingInterventions } from "./shared.ts";
```
Elsewhere in the codebase we don't include any file extension. If I import `from "./shared"`, then `npm run check` is happy, but `npm run test` breaks. With this PR, both `check` and `test` appear to be happy.
I don't understand why Playwright is doing anything special here. Only relevant thing I could find is https://github.com/microsoft/playwright/issues/19710. So, this PR seems fine, unless one of us understands TS build config better.
=> Fix TS errors involving shared.ts

src/lib/draw/AttributeMode.svelte, tests/modes.spec.ts
See the test for a description of the bug. We zoom to an object when opening it from the sidebar. But while the form is open, if you move or zoom the map and then click anything in the open form, we zoom again. This PR adds a test and fixes the problem.
=> Fix bug where we zoom to an object at the wrong time

src/lib/sidebar/InterventionList.svelte, src/schemas/criticals.json, src/schemas/criticals.ts
This makes things consistent with other modes, but we still need to improve the UX for filling out criticals. Having to name something is an extra step that people may not want to do? Maybe there's no meaningful name, and instead the sidebar should list things differently. Filtering to show by type of critical, or some resolution status, etc could be more relevant.
=> Let critical issues be nameable

package-lock.json, package.json, src/lib/common/Modal.svelte
Closes #188. I upgraded to MapLibre 3 a few weeks ago in https://github.com/dabreegster/osm2svelte and haven't seen any issues. There are new API calls like https://maplibre.org/maplibre-gl-js-docs/api/sources/#geojsonsource#updatedata that we might take advantage of in the future.
Also upgrades to the new [Svelte 4](https://svelte.dev/blog/svelte-4). No big new changes, but possibly a few places where we can get [better TS support](https://svelte.dev/docs/v4-migration-guide).
No behavioral changes I can notice from manually playing around or running tests.
=> Update most NPM dependencies

src/pages/App.svelte, tests/errors.spec.ts
See bug for details. To repro the problem, draw a route crossing the Meadows and look for the thick "bulge" near intersections.
Before this PR:
https://acteng.github.io/atip/scheme.html?authority=Surrey&schema=v1#18.69/51.2285668/-0.5773313
After this PR (give github a few mins to deploy):
https://acteng.github.io/atip/fix_route_snappers/scheme.html?authority=Surrey&schema=v1#20.17/51.2287442/-0.5778096
The fix is in the other repo, https://github.com/dabreegster/route_snapper/pull/34.
=> Use new route snapper data to fix #255

src/lib/draw/HoverLayer.svelte, src/lib/draw/StreetViewMode.svelte, src/lib/draw/Toolbox.svelte, src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/SplitRouteMode.svelte, src/maplibre_helpers.ts
A followup to #246. Change the cursor for most of our tools to indicate the current interactions possible on the map. Showing a few off, but easiest to just try at https://acteng.github.io/atip/curses_and_cursors/scheme.html?authority=Adur:
https://github.com/acteng/atip/assets/1664407/346cce17-8ab2-495f-9f8d-9b10a51d95d7
In general I tried to mimic design choices made by geojson.io (mapbox-gl-draw), Felt, terra-draw.
=> Use cursors in most tools

src/pages/App.svelte, src/types.ts
See issue for details. We don't want most users to change the schema right now; if someone's using something other than v1, we'll send them a URL with instructions. But all the same, if someone has used ATIP in multiple modes, we want to communicate somewhere which schema they're working with.
Changes to text styling or wording are welcome!
=> Replace the schema dropdown with a title for the current mode. #254

src/colors.ts, src/lib/draw/InterventionLayer.svelte, src/lib/layers/SpeedLimits.svelte, src/maplibre_helpers.ts
Kelin (UA programme manager with an architecture background) kindly joined a UX session, and we generated lots of ideas to improve ATIP. Here are a few simple ones.
First, change the colors for routes and areas, and add an outline to areas. The outline emphasizes it as a clickable object more, and matches how Felt looks. Before:
After:
And second, change the color scale used for showing speed limits. It's based on the first big map in https://knightlab.northwestern.edu/2016/07/18/three-tools-to-help-you-make-colorblind-friendly-graphics/, but we adjusted the middle color, since it's too close to the basemap background color. We adjusted it by using the "mix" tool in `gpick`, mixing it with the category for 40 mph. Before:
After:
Also note that the new color for routes (grey) is sort of a …
=> Color adjustments from Kelin

src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/SplitRouteMode.svelte, src/maplibre_helpers.ts
For #252. Trim to 6 decimal places recommended by the GJ spec.
https://github.com/dabreegster/route_snapper/pull/38 did this for the route and snapped polygon tool, but it's not included in ATIP yet (I'll make another few changes and then release a new NPM version). This PR does it for the point, freehand polygon tool, and when splitting routes.
I thought about also doing this transformation in the backfill routine (when we load a GJ file from somewhere), but I don't think it's as important. If/when we have a story about storing official submitted data in one central place, we could do the transformation there.
Tested by drawing/splitting stuff, exporting, and manually checking the file
=> Trim coordinate precision for drawing points and freehand polygons

.github/workflows/playwright.yml, .github/workflows/web.yml, .gitignore, browse.html, docs/developer_guide.md, package-lock.json, package.json, src/pages/BrowseSchemes.svelte, src/style/main.sass
https://frontend.design-system.service.gov.uk/get-started. Very lightly change the browse scheme page typography using Sass, to preview the next steps for integration.
This is an alternative to #258. Because switching is going to take a few steps, I propose we do it gradually. The build setup is subtle enough to deserve its own step. After this PR, I propose we update the two simple pages (scheme browsing and choosing an area) to completely use govuk styles, figuring out some of the patterns for using Sass vs Svelte components. Then tackle the much more complex main page.
Preview: https://acteng.github.io/atip/govuk_frontend_v2/browse.html
The text style changes slightly:
I have also temporarily copied in https://design-system.service.gov.uk/components/accordion to test the JS integration …
=> Get govuk installed, following

.github/workflows/playwright.yml, .github/workflows/web.yml
The deploy web workflow in https://github.com/acteng/atip/actions takes around 15 minutes lately, dependent on the number of open branches we've got. This PR uses [GH caches](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) to at least save the initial step of building the Rust route-info crate.
Much of the time is unfortunately spent in a `wasm-opt` step, which doesn't look like it's good at figuring out no source has changed and short-circuiting. This new cache step can't hurt, though.
=> Cache the WASM build in Github Actions. #223

index.html, src/lib/ZoomOutMap.svelte, src/lib/common/CollapsibleCard.svelte, src/lib/common/FileInput.svelte, src/lib/common/Modal.svelte, src/lib/govuk/DefaultButton.svelte, src/lib/govuk/FormElement.svelte, src/lib/govuk/Radio.svelte, src/lib/govuk/SecondaryButton.svelte, src/lib/sidebar/About.svelte, src/lib/sidebar/EntireScheme.svelte, src/pages/BrowseSchemes.svelte, src/pages/ChooseArea.svelte, src/style/main.sass, tests/savefiles.spec.ts
This is the next step to use the govuk design system, on our two simpler pages. I've tried my best to interpret https://design-system.service.gov.uk/styles/ and https://design-system.service.gov.uk/components/, but I (really hope!) we go through some kind of design review later, because there are plenty of unclear decisions made.
Compare: [old homepage](https://acteng.github.io/atip/index.html) with [new homepage](https://acteng.github.io/atip/govuk_step2/index.html), and [old browse](https://acteng.github.io/atip/browse.html) with [new browse](https://acteng.github.io/atip/govuk_step2/browse.html)
https://github.com/acteng/atip/assets/1664407/181d3c35-6d86-4e11-93ef-0b540c08663f
In the step after this one, I'll convert our main edit page... or at least the sidebar. I haven't found much …
=> Convert the scheme browse and area choose page to govuk style

src/lib/draw/AttributeMode.svelte, src/lib/draw/GeometryMode.svelte, src/lib/draw/Toolbox.svelte, src/lib/sidebar/EntireScheme.svelte, src/lib/sidebar/Instructions.svelte, src/pages/App.svelte, src/types.ts, tests/modes.spec.ts, tests/shared.ts
See #160.
I think I got the tests, but slow internet at the moment, so can't run easily
=> Use a different word for intervention per schema. #160

src/lib/govuk/Select.svelte, src/pages/BrowseSchemes.svelte
Inspired by yesterday, this is a small improvement to the scheme browse page. Beside free-text filtering, also filter by two particular fields in the input data:
https://github.com/acteng/atip/assets/1664407/a0c16b66-a3dd-4a41-9479-e53eeb69fc3f
My goal is to flesh out a few more improvements to this page ahead of next week's meetings, so we can explore more possible directions to take this.
To try it out, https://acteng.github.io/atip/browse_dropdown_filters/browse.html and load magicfoo.geojson (from emails/Sharepoint). Motivation to make progress on auth soon :)
=> Add some dropdown filters to the scheme browsing page

package-lock.json, package.json, src/lib/forms/AutogenerateForm.svelte
Closes #273 
https://acteng.github.io/atip/capitalize_auto_form/scheme.html?authority=Adur&schema=v2
An incremental improvement. It'd also be nice to apply these to radio buttons, so we don't see `SchoolCrossing`. But we need to be careful with https://github.com/sindresorhus/humanize-string, because it mangles the dash in "20 - 30 mph"
=> Display user-friendly field names for auto-generated forms

.github/workflows/playwright.yml, src/lib/draw/GeometryMode.svelte, src/lib/draw/Toolbox.svelte, src/lib/draw/common.ts, src/lib/draw/event_handler.ts, src/lib/draw/route/RouteMode.svelte, src/lib/govuk/TextInput.svelte, src/lib/layers/LaneDetails.svelte, src/lib/layers/SpeedLimits.svelte, src/lib/sidebar/InterventionList.svelte, src/pages/App.svelte, src/pages/ChooseArea.svelte, src/stores.ts, tests/savefiles.spec.ts, tsconfig.json
Closes #89.
In recent PRs, there have been some simple errors that TS would've caught, but we're not enforcing checks yet. My goal here is to catch new problems with as many compile-time warnings as possible. There are still some difficult cases for us to fix, but we can `@ts-ignore` them and treat them as TODOs.
=> Enable TS strict mode and enforce it with GH actions

src/lib/browse/Filters.svelte, src/lib/browse/SchemeCard.svelte, src/lib/browse/data.ts, src/lib/forms/FormV1.svelte, src/maplibre_helpers.ts, src/pages/BrowseSchemes.svelte, src/types.ts
#173. This splits the monolithic Svelte component with TS checks disabled into a few logical components, and fixes all TS errors. Not much behavioral change yet, other than simplifying the map tooltips to only show the meaningful fields.
=> Refactor the scheme browse page

src/lib/BaselayerSwitcher.svelte, src/lib/Legend.svelte, src/lib/ZoomOutMap.svelte, src/lib/browse/Filters.svelte, src/lib/browse/SchemeCard.svelte, src/lib/common/ConfirmationModal.svelte, src/lib/common/FileInput.svelte, src/lib/common/Modal.svelte, src/lib/common/index.ts, src/lib/draw/StreetViewMode.svelte, src/lib/draw/point/PointControls.svelte, src/lib/draw/polygon/PolygonControls.svelte, src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/SplitRouteMode.svelte, src/lib/draw/snap_polygon/SnapPolygonControls.svelte, src/lib/forms/FormV1.svelte, src/lib/forms/RouteInfoLayers.svelte, src/lib/govuk/Select.svelte, src/lib/govuk/index.ts, src/lib/layers/ContextualLayers.svelte, src/lib/layers/LaneDetails.svelte, src/lib/layers/SpeedLimits.svelte, src/lib/sidebar/About.svelte, src/lib/sidebar/EntireScheme.svelte, src/lib/sidebar/Instructions.svelte, src/lib/sidebar/InterventionList.svelte, src/pages/App.svelte, src/pages/BrowseSchemes.svelte, src/pages/ChooseArea.svelte
Makes using these common libraries less verbose. https://javascript.info/import-export#re-export talks about this approach.
=> Mechanical refactor to group imports from common and govuk directories

src/lib/Legend.svelte, src/pages/App.svelte, src/pages/BrowseSchemes.svelte
Layer controls are often a map overlay, like in https://www.planning.data.gov.uk/map. We use that today for switching basemaps and showing a legend, but the speed limit layer is smushed into the sidebar for no good reason. Group everything and make the entire overlay hideable.
https://github.com/acteng/atip/assets/1664407/12fe6689-530e-4c73-ad09-7f575a24dfa7
=> Consolidate 3 layer-like controls

src/lib/browse/Filters.svelte, src/lib/browse/OptionalLayer.svelte, src/lib/browse/SchemeCard.svelte, src/lib/common/data_getter.ts, src/pages/App.svelte, src/pages/BrowseSchemes.svelte
First off, our free-form text filter is confusing before this PR. If you search for "school", you see things on the map that just happen to be in the same scheme that mentions schools. This PR changes it so that you _only_ see interventions mentioning that word. And to make that clear, highlight the search result in the popup.
Second, I flipped the optional layers to be disabled by default. We can revisit this as we have more of them and understand how they're used, but at the moment, I think they're a distraction when loading scheme data.
Third, the "edit on map" button is disabled when the authority name is incorrect, so people don't even click and later get an error. I'd very much like to fix the root cause here and rebuild the all-scheme dataset from its original input, but this is a …
=> Some usability improvements for browse page

package-lock.json, package.json, src/random_schemes.ts
Just a quick script to churn out vaguely sensible looking example data. We can use this to explore GCP deployment in the short-term, performance-test the browse page, take videos for GH pull requests, etc.
https://github.com/acteng/atip/assets/1664407/b4fb9751-eb23-40d1-b2bd-1bd33d788be4
=> Generate random data for the scheme browse page

src/lib/browse/BusRoutesLayerControl.svelte, src/lib/browse/colors.ts, src/maplibre_helpers.ts, src/pages/BrowseSchemes.svelte
Demo at https://acteng.github.io/atip/bus_routes/browse.html
Two colors and a tooltip to indicate if each road involving some bus route has a dedicated lane or not. Not attempting yet to show _direction_ of the bus lane. We could consider arrows or lines clearly on the left or right side of a road to do this in the future, or even showing a full-blown schematic like streetmix.net or osm2streets.org on hover.
The line width is kind of thick and awkward at low zooms. Existing problem with MRN too; might followup with a separate PR and try out changing width based on zoom level.
=> Add a layer showing bus routes with and without bus lanes

.prettierignore, src/lib/browse/CycleParkingLayerControl.svelte, src/lib/browse/colors.ts, src/maplibre_helpers.ts, src/pages/BrowseSchemes.svelte
Demo: https://acteng.github.io/atip/parking/browse.html
References:
- https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking
- https://bikedata.cyclestreets.net/tflcid/conversion/#cycle_parking
- https://bikedata.cyclestreets.net/cycleparking/#16.88/51.511361/-0.102809
I've chosen to only show capacity, not details like type, covered, public/private. We can extend this later with feedback.
Design-wise, only a few points are shown at low zoom, and at high zoom, the dots are not terribly significant. I think symbolic icons and https://maplibre.org/maplibre-gl-js/docs/examples/cluster/ will help with both issues, and also potentially be useful for other layers. We can explore them later.
=> Cycle parking layer

src/pages/BrowseSchemes.svelte
The data entry and browse functions have different audiences, so it's just confusing to have this button
=> Remove home button from browse page

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/VehicleCountsLayerControl.svelte, src/lib/maplibre/utils.ts
Demo: https://acteng.github.io/atip/vehicle_counts/browse.html
https://github.com/acteng/atip/assets/1664407/2f8c5780-dcdb-4a95-9055-177f21ffe024
This should be enough to start, but plenty of next steps:
- icons instead of points
- display all points when unzoomed (or at least some kind of clustering or heatmap to indicate where the points are)
- adjust the buckets -- not seeing the higher values much
=> Add a vehicle counts layer. #318

critical_entry.html, docs/architecture.md, src/lib/common/Layout.svelte, src/lib/common/StreetViewController.svelte, src/lib/critical_entry/BaselayerSwitcher.svelte, src/lib/critical_entry/Form.svelte, src/lib/critical_entry/LocationDescription.svelte, src/lib/critical_entry/Pin.svelte, src/lib/govuk/Select.svelte, src/lib/govuk/TextArea.svelte, src/lib/maplibre/layer_helper_utils.ts, src/pages/CriticalIssueEntry.svelte, vite.config.ts
Demo at https://acteng.github.io/atip/critical_entry_mvp/critical_entry.html. A start to #322:
https://github.com/acteng/atip/assets/1664407/7c6b7b41-d9e9-4dfc-9b5a-092e6dab962b
Pasting the resulting row in the xlsx appears to work for me, but of course we should test more carefully end-to-end before recommending people use this.
Future steps:
=> Start a page for critical issue entry

src/lib/browse/layers/CombinedAuthoritiesLayerControl.svelte, src/lib/browse/layers/LocalAuthorityDistrictsLayerControl.svelte, src/lib/browse/layers/LocalPlanningAuthoritiesLayerControl.svelte, src/lib/browse/layers/ParliamentaryConstituenciesLayerControl.svelte, src/lib/browse/layers/WardsLayerControl.svelte
This is design advice from @stuartlynn. Filling the boundaries with a color doesn't do anything useful, and potentially obscures other layers. Hovering on an area still works the same.
Demo: https://acteng.github.io/atip/hover_boundaries/browse.html
Before (scheme data with wards):
After:
=> Don't draw filled polygons for boundary layers, just outlines.

package-lock.json, package.json, src/lib/draw/GeometryMode.svelte, src/lib/draw/common.ts, src/lib/draw/route/RouteMode.svelte, src/lib/forms/FormV1.svelte, src/pages/SketchSchemes.svelte, src/stores.ts, tests/errors.spec.ts, tests/modes.spec.ts
This is a followup to #352. We're going to remove the `route-info` WASM library, which only has one useful working feature: auto-naming routes based on the two intersection endpoints. This PR changes that feature to instead use a new version of the route-snapper library. It also slightly improves the UX, by populating the name automatically when a route is first made. Users can still override the name, or later auto-fill it (to correct things after a split, for instance).
The benefits to dismantling the route-info service are:
- Page load performance: almost half the amount of data to load, because now we only load a route snapper graph, not a second file. The snapper file has grown slightly now that it has names, but it's a small increase when gzipped, and the overall change is way less …
=> Use new route-snappers, revamping how auto-named routes work

src/lib/browse/data.ts
specific and make it hard to interact with smaller interventions
Test with all_scheme_data.geojson
=> Manually filter out some huge areas that don't describe anything

package-lock.json, package.json, src/lib/common/Geocoder.svelte, src/lib/common/index.ts, src/pages/BrowseSchemes.svelte
#288 
I started with maplibre-gl-geocoder and Nominatim API, following https://maplibre.org/maplibre-gl-js/docs/examples/geocoder/, but the plugin's UX was clunky and results from Nominatim are not great. Since we're using MapTiler for some basemaps anyway and already have an API key, I decided to try their plugin + API instead, and I think it works much more smoothly.
Try at https://acteng.github.io/atip/geocoder_maptiler/browse.html. It's still imperfect, but I think this is enough to start.
=> Add a geocoder using MapTiler

src/lib/browse/InterventionLayer.svelte, src/lib/browse/LayerControls.svelte, src/lib/browse/layers/areas/CensusOutputAreas.svelte, src/lib/browse/layers/areas/CombinedAuthorities.svelte, src/lib/browse/layers/areas/IMD.svelte, src/lib/browse/layers/areas/LocalAuthorityDistricts.svelte, src/lib/browse/layers/areas/LocalPlanningAuthorities.svelte, src/lib/browse/layers/areas/ParliamentaryConstituencies.svelte, src/lib/browse/layers/areas/Wards.svelte, src/lib/browse/layers/lines/BusRoutes.svelte, src/lib/browse/layers/lines/CyclePaths.svelte, src/lib/browse/layers/lines/MajorRoadNetwork.svelte, src/lib/browse/layers/lines/PCT.svelte, src/lib/browse/layers/lines/RoadSpeeds.svelte, src/lib/browse/layers/lines/RoadWidths.svelte, src/lib/browse/layers/points/CriticalIssues.svelte, src/lib/browse/layers/points/Crossings.svelte, src/lib/browse/layers/points/CycleParking.svelte, src/lib/browse/layers/points/PolygonAmenityLayerControl.svelte, src/lib/browse/layers/points/VehicleCounts.svelte, src/lib/common/index.ts, src/pages/CriticalIssueEntry.svelte, src/pages/SketchSchemes.svelte
- When there are overlapping layers, only let the topmost one have interactions. (I accidentally lost this behavior during the svelte-maplibre shuffle, when switching from my fork to the upstream)
- Add the geocoder to critical entry and sketch pages
- Add the line measure tool to the critical entry page (but it partly breaks / conflicts with the main tool there)
Demo at https://acteng.github.io/atip/topmost/browse.html
=> A few UX fixes

.github/workflows/deploy_appengine.yml, backend/README.md, backend/app.yaml
Via following https://github.com/google-github-actions/deploy-appengine. To note, I tried using the newer workload identity federation option, but the documentation is antagonistically dense.
Pete, you'll need to update the project number in this PR please! I tested with my own project, but we won't be able to really try this out for the real test environment without merging (because it's set to only trigger for the main branch).
=> Automatically deploy App Engine for test environment

package-lock.json, package.json, src/lib/browse/LayerControls.svelte, src/lib/browse/layers/areas/Pollution.svelte, src/lib/maplibre/zorder.ts
#368. Demo at https://acteng.github.io/atip/defra/browse.html.
It would be much nicer to show a value by the mouse as you move around, but these pre-built raster layers served through WMS don't easily support it. We could try out the `GetFeatureInfo` API in the future (maybe on-click; as you hover won't be fast enough). Or we could process the raw data ourselves and produce raster tiles in some format that's easier to query.
It would also be nice to match the NOx metric used by inspections: >40, 40-32, <32. But again with prebuilt raster data, we can't do much.
Note this PR contains an attempt at the noise layer from http://www.extrium.co.uk/noiseviewer.html. It's disabled for two reasons:
1) I'm not sure they mean for it to be used publicly, even though the WMS server happily serves …
=> Add pollution layers

src/lib/sidebar/EntireScheme.svelte, src/pages/ChooseArea.svelte, src/pages/SketchSchemes.svelte, tests/homepage.spec.ts
Two quick fixes:
1) If you go the homepage with ?schema=foo, then we preserve that when you click an area. Otherwise our partner will have to manually add `schema=pipeline` in the near-future
2) Stop using .txt for downloaded files. This was something we did for better compatibility with SmartSurvey. Since we're not using a  new version of the sketch tool anytime soon, let's use .geojson, so people understand what the files are and they work with normal GIS tools
=> Plumb along schema in URL

src/lib/sidebar/PipelineListMode.svelte, src/lib/sidebar/PipelineSchemeDetails.svelte, src/lib/sidebar/Superscheme.svelte, src/lib/sidebar/scheme_data.ts, tests/pipeline_sketching.spec.ts
Change subscheme to scheme when giving default name to "sub"schemes
Don't require user to expand 'sub'scheme to see its interventions
=> Superscheme tidy up

src/lib/common/Geocoder.svelte, src/lib/forms/PipelineForm.svelte, src/lib/govuk/FormElement.svelte, src/lib/govuk/NumberInput.svelte, src/lib/govuk/Radio.svelte, src/lib/govuk/TextInput.svelte, src/lib/govuk/index.ts, src/lib/sidebar/EditForm.svelte, src/lib/sidebar/EntireScheme.svelte, src/lib/sidebar/PipelineSchemeForm.svelte, src/lib/sidebar/UnexpectedProperties.svelte, src/lib/sidebar/scheme_data.ts, src/pages/SketchSchemes.svelte, src/types.ts
Demo at https://acteng.github.io/atip/pipeline_form_updates/scheme.html?authority=TA_Portsmouth&schema=pipeline
This fixes some problems from #380:
- Makes sure changes to the scheme fields get saved and cleared properly
- Make the "Scheme details" more prominent and let people know when there's missing data
- Adjusts form field labels (everywhere)
- Improves the numeric input
- Adjusts some of the questions based on latest data doc
Edit: and a few more things pre-workshop:
- Make the geocoder position on the sketch page actually usable
- Escape key for the scheme details modal
- Show per-intervention warnings for pipeline mode
=> Pipeline form updates

package-lock.json, package.json, src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/RouteSnapperLoader.svelte, src/lib/draw/route/route_tool.ts, src/lib/draw/route/stores.ts, src/lib/draw/snap_polygon/SnapPolygonControls.svelte, src/stores.ts
https://github.com/acteng/atip/assets/1664407/01c17c13-4e84-46a2-a817-a63e396ce1bc
https://acteng.github.io/atip/route_snapper_undo/scheme.html?authority=LAD_Adur
#44
Here's a simple first step. We can do the same for the freehand polygon and point tools (or maybe not worth it), then sliiightly harder will be for forms / list mode.
=> Undo in route snapper / area tools

src/pages/SketchSchemes.svelte
This works fine locally, but when we're hosted on GH, relative URL becomes important.
Test: https://acteng.github.io/atip/scheme.html?authority=oops
=> Fix redirect for bad authority name

assets/image.svg, src/lib/draw/Toolbox.svelte, src/lib/draw/image/ImageLayer.svelte, src/lib/draw/image/ImageMode.svelte, src/lib/draw/image/stores.ts, src/lib/sidebar/LeftSidebar.svelte, src/pages/SketchSchemes.svelte, src/types.ts
#389 
Demo: https://acteng.github.io/atip/move_images_v3/scheme.html?authority=LAD_Adur
Here's an example from Hackney: https://consultation.hackney.gov.uk/streetscene/butterfield-green/results/butterfieldgreen-delegatedpowersdecision.docx2.pdf
It took me a bit to align things, but here's a demo of how it looks in the end:
https://github.com/acteng/atip/assets/1664407/48490635-7291-4df7-9bf3-a4c92541c65c
This is just a first cut. Next, I'll work on picking any two control points on the raw image, then finding the same places on the map. Going by corners is hard!
=> Let the user temporarily add an image to the map for georeferencing

src/lib/draw/polygon/polygon_tool.ts
(cf. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions)
=> Use const assertion to force narrow type inference

src/lib/sidebar/ListMode.svelte, src/lib/sidebar/PerSchemeControls.svelte
Currently have logic lifted to ListMode because it feels like that's what should be managing the order of schemes but I don't mind putting it in PerSchemeControls if we prefer
=> Allow reordering of schemes in list

src/pages/SketchSchemes.svelte
When you have several schemes in sidebar, you can easily scroll to show whitespace and have some of the map, and the tools hidden. This fixes that
=> prevent scrolling below the map

src/lib/browse/InterventionLayer.svelte
Oops sorry, broke in #411. We switched to the new maplibre style expressions, but I forgot to update some of the old-style ones in browse. Mixing the two doesn't work. I really wish there was a way to detect the new/old expressions in the static type system or at least with a runtime error, but I don't think maplibre does that.
I've noticed a bug where loading the GJ file in browse doesn't show stuff in the sidebar. I think that predates #411, I'll have a quick look separately
=> Fix browse page layer display

src/lib/sidebar/PerSchemeControls.svelte
Adding an indication of whether a listed intervention in 'an alternative' so that users can easily know if they've set that flag
=> Add indicator for alternative intervention options

src/lib/browse/layers/areas/CensusOutputAreas.svelte, src/lib/browse/layers/areas/IMD.svelte, src/lib/common/MapLibreMap.svelte
I was looking into why we don't seem to get any style validation errors from maplibre, and it turns out svelte-maplibre is intercepting them and re-dispatching. This prevents maplibre's default behavior of console logging when there are no handlers. So, this PR starts logging errors. There were a few easy bugs on the browse page, now fixed. This logging would've prevented #415 or made it much easier to figure out the problem
=> Actually log Maplibre errors

package-lock.json, package.json, src/pages/SketchSchemes.svelte, tests/errors.spec.ts, tests/modes.spec.ts
I made a new route-snapper release recently (https://github.com/dabreegster/route_snapper/pull/47) that avoids unnecessary coordinate projection and produces more accurate lengths. This updates ATIP to use it. I've generated and uploaded the v2.5 files for everywhere with https://github.com/acteng/atip-data-prep/pull/43.
Manual tests in different areas all work fine
=> Update route-snappers package and use new files

src/lib/browse/Filters.svelte, src/lib/browse/InterventionLayer.svelte, src/lib/browse/InterventionPopup.svelte, src/lib/browse/LayerControls.svelte, src/lib/browse/stores.ts, src/pages/BrowseSchemes.svelte, src/stores.ts
When we switched over to svelte-maplibre, the filter by freeform text feature partly broke. When you hover on a matching feature, the filter text is supposed to be highlighted. Now it is again.
I'm not entirely sure why using a store works, but there's some subtlety with svelte-maplibre and Popups. A store is simpler anyway; less prop drilling.
=> Fix filter text highlighting in popup

src/lib/browse/Filters.svelte, src/lib/browse/InterventionColorSelector.svelte, src/lib/browse/InterventionPopup.svelte, src/lib/browse/colors.ts, src/lib/browse/data.ts
Coloring by funding was a bit broken and not reactive to new cases like "ATF2 or ATF3" and "LCWIP". Also add a total length count to the `Showing 639 schemes (5,811 routes, 184 areas, 0 crossings, 147 other, with total LineString length of 6606.7 miles)` checkbox, since it's maybe of interest. (But if it's just confusing, will remove)
=> Include new funding programme and a total length in the browse page

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/lines/CyclePaths.svelte
As requested in the demo last week:
https://github.com/acteng/atip/assets/1664407/76f8d7db-0553-478b-a4e3-0a6fcb5736f8
Also fixed the checkbox size for the last two groups, because it was inconsistent:
=> Toggle cycle layers individually

src/pages/ChooseArea.svelte, tests/homepage.spec.ts, tests/pipeline.spec.ts
The problem our user hit:
1) They sketched geometry using the v1 tool, somehow messing up the URL to not be in pipeline mode
2) They loaded the file with the correct pipeline mode URL, but then the pipeline forms didn't show up
=> Fix bug detecting schema

src/lib/browse/LayerControls.svelte, src/lib/maplibre/zorder.ts
My connection is too sad to upload the demo video, so -- enable some layers with tooltips/clicking/etc. Then enable street view and verify that the other layers now aren't interactive. Disable stview, and they're interactive again.
This was a regression when we switched to svelte-maplibre, finally fixing it
=> Disable other layers when streetview is enabled. #359

src/lib/browse/Filters.svelte, src/lib/browse/InterventionPopup.svelte, src/lib/browse/SchemeCard.svelte, src/lib/browse/data.ts, src/lib/browse/stores.ts, src/types.ts
A few requested changes:
- Emphasize scheme name, not the reference, in the sidebar. Most people don't know the reference offhand.
- Stop showing "scheme X has 4 features." That's not useful to anyone.
- Add a free-text filter for scheme name or reference
**Before merging**, I want to see if scheme name is ever blank, because then the SchemeCard title will be hard to click. We could fallback to the reference? Or maybe this never happens; we can assert in aatip-scheme-data and update the TS if so.
Demo: https://acteng.github.io/atip/browse_show_diff_stuff/browse.html
=> Don't forget about scheme name

src/lib/browse/colors.ts, src/lib/browse/layers/points/Crossings.svelte
Make it easier to see signalized, by request.
I was going to distinguish zebras as well, but we're not including enough raw OSM tags. We should probablydo the classification in the data-prep side.
=> Distinguish some crossing types

browse.html, critical_entry.html, index.html, package-lock.json, package.json, scheme.html, src/style/main.sass, tests/pipeline.spec.ts, tests/settings.spec.ts
Other than the alpha button changing style a bit, I don't notice any behavioral changes.
You'll need to `npm i; npm run setup-govuk` locally after this is in
Full changelog in https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md. I skimmed through and didn't spot anything that should affect us
=> Upgrade govuk-frontend

package-lock.json, package.json
Again no noticeable changes.
I'll stop for now, because blocked or stuck on the last ones.
- Things related to vite break when I upgrade, because `vite-plugin-wasm-pack` (needed for the route snapper) isn't compatible with the new vite. That plugin is pretty unmaintained and causing me headaches in other projects, so eventually I'll try to just fix it upstream, but not now
- `@tsconfig/svelte` stops seeing the TS definitions for all the turf dependencies, and I don't want to struggle through tsconfig right now to figure it out
- maplibre 4 is out, and there's a PR for support in svelte-maplibre. We can wait a few days and then try it out.
=> A few more upgrades

src/lib/forms/PipelineForm.svelte, src/lib/sidebar/PipelineSchemeForm.svelte, src/lib/sidebar/pipeline/BudgetForm.svelte, src/lib/sidebar/pipeline/TimingForm.svelte, src/lib/sidebar/scheme_data.ts, src/types.ts, tests/data/pipeline_before_feb_fields.geojson, tests/pipeline.spec.ts, tests/shared.ts
As requested by our user. I referred to #398 but didn't preserve the behavior of aggregating per-feature timing/budget to inform the scheme-wide variant. We could consider adding this back if it's requested, but I'm not sure if there are situations when the values are known both overall and individually.
I added some tests and checked old files, but please also do test things out carefully
=> Include optional budget and timing forms for each intervention

src/lib/draw/route/RouteControls.svelte, src/lib/sidebar/pipeline/TimingForm.svelte
By request. Note if the value is required (scheme-level), "Unknown" still produces a warning:
=> Allow users to deselect the timing and status radio buttons

package-lock.json, package.json, src/lib/browse/layers/points/CriticalIssues.svelte
Was waiting on a geocoder dependency to get support, but now we can do this. https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md lots of changes, most invisibly handled in svelte-maplibre already
=> Upgrade to maplibre 4

src/lib/browse/layers/points/VehicleCounts.svelte
Just the first task from #482. Before pushing, we need to update the pmtiles file
=> Update vehicle counts layer to show all years and emphasize data source

backend/server.js, src/lib/browse/LoadRemoteSchemeData.svelte
As fate would have it, we're forced to look at #493 immediately, because we're now over the 32MB app engine response limit. If we gzip that file, it's down to about 7MB and loads much faster on slow connections anyway!
Do `gzip --keep all_schemes_output.geojson` after running the combine script, and upload that to the same `private_layers/v1/` folder. Please test in the dev environment first, deploy this PR manually (backend/README has instructions), make sure everthing works end-to-end, then push to test env
=> Use gzipped scheme data

src/lib/browse/DescribePipelineBudget.svelte, src/lib/browse/DescribePipelineTiming.svelte, src/lib/browse/InterventionPopup.svelte
A start towards #493. The extra LCWIP fields are invisible now; this at least starts showing them in per-feature popups. Also added bolding to values, to try and be consistent with the style for other browse popups.
I don't know if this way of presenting information is useful, but it seems better than not showing anything
=> Show LCWIP fields in browse popups

src/lib/browse/layers/lines/PavementWidths.svelte
Needs the new pmtiles, of course
=> Indicate the side of road for pavement width

package-lock.json, package.json, src/lib/draw/EditGeometryMode.svelte, src/lib/draw/route/SplitRouteMode.svelte
I moved the core split logic upstream. This passes manual tests. (We don't have any playwright tests of splitting. Eventually there ought to be unit tests just for the split logic, but not in this repo.)
=> Move route split logic to upstream TS package

src/lib/browse/layers/areas/CensusOutputAreas.svelte, src/lib/browse/layers/areas/CombinedAuthorities.svelte, src/lib/browse/layers/areas/IMD.svelte, src/lib/browse/layers/areas/LocalAuthorityDistricts.svelte, src/lib/browse/layers/areas/LocalPlanningAuthorities.svelte, src/lib/browse/layers/areas/ParliamentaryConstituencies.svelte, src/lib/browse/layers/areas/Pollution.svelte, src/lib/browse/layers/areas/RoadNoise.svelte, src/lib/browse/layers/areas/Wards.svelte, src/lib/browse/layers/lines/BusRoutes.svelte, src/lib/browse/layers/lines/CyclePaths.svelte, src/lib/browse/layers/lines/Gradients.svelte, src/lib/browse/layers/lines/MajorRoadNetwork.svelte, src/lib/browse/layers/lines/NationalCycleNetwork.svelte, src/lib/browse/layers/lines/PCT.svelte, src/lib/browse/layers/lines/PavementWidths.svelte, src/lib/browse/layers/lines/RoadSpeeds.svelte, src/lib/browse/layers/lines/RoadWidths.svelte, src/lib/browse/layers/lines/StrategicRoadNetwork.svelte, src/lib/browse/layers/lines/Trams.svelte, src/lib/browse/layers/points/BusStops.svelte, src/lib/browse/layers/points/Crossings.svelte, src/lib/browse/layers/points/CycleParking.svelte, src/lib/browse/layers/points/Education.svelte, src/lib/browse/layers/points/PolygonAmenityLayerControl.svelte, src/lib/browse/layers/points/RailwayStations.svelte, src/lib/browse/layers/points/Stats19.svelte, src/lib/browse/layers/points/VehicleCounts.svelte, src/lib/browse/layers/url.ts
Demo: https://acteng.github.io/atip/browse_layer_urls/browse.html?style=dataviz&crossings=1&stats19=other%2F2019%2F2022&road_noise=1#5.69/53.021/-1.825
This syncs up the state of browse layers with URL query parameters. This makes URLs much more reproducible/shareable, and is a step towards linking directly to the browse page (or embedding in an iframe?) from route check.
Note:
- If someone changes the URL, there's a full page refresh. We could squeeze everything into the URL fragment if we wanted to change this, but I don't think there's a use case for it
- No change for the critical issues layer, because that requires a custom file input
- We can't use a single query param (like `layers=x,y,z`) because some layers have more details
- The URL as it is now isn't quite reproducible, …
=> Capture browse layer state in the URL

src/lib/browse/LoadRemoteSchemeData.svelte, src/lib/common/index.ts, src/lib/draw/route/RouteSnapperLoader.svelte
1) Add a progress bar to the browse page
2) Add a URL parameter `disable_schemes=1` to not do this automatically, for later use in inspectorate tools
I had to use https://www.danvega.dev/blog/network-throttling#chrome-devtools to test the progress bars, but if you have access to naturally slow internet, even easier ;)
Demo of second feature: https://acteng.github.io/atip/pipeline/browse.html?disable_schemes=1
=> Improve browse page loading experience

src/lib/draw/EditGeometryMode.svelte, src/lib/draw/InterventionLayer.svelte, src/lib/draw/config.ts, src/lib/draw/point/PointMode.svelte, src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/PolygonMode.svelte, src/lib/draw/route/RouteMode.svelte, src/lib/draw/route/SplitRouteMode.svelte, src/lib/draw/snap_polygon/SnapPolygonMode.svelte, src/lib/draw/stores.ts, src/lib/draw/types.ts, src/lib/maplibre/utils.ts, src/lib/sidebar/scheme_data.ts, src/types.ts
I want to move the bulk of the scheme sketcher code into a new git repo, exposed as a Sveltekit library. The goal is to more easily use pieces of this from other projects, such as the inspectorate tools. It's not an easy refactor; the bulk of the core drawing logic is already in `maplibre-draw-polygon` and `route-snapper`, but the code here manages the toolbox, switches modes, manages the store with the GeoJSON features, etc.
Roughly the split of responsibility I picture is like this. The sketch library will handle `lib/draw/` and parts of `lib/sidebar` -- giving people the mode switching logic, multi layer (scheme) management, sidebar controls, etc. What will remain in this repo (and have a new, much simpler variation in inspectorate tools) is per-schema forms, backfilling logic, etc. So …
=> Start refactoring scheme sketcher code, before moving to a library

src/lib/browse/layers/lines/BusRoutes.svelte, src/lib/browse/layers/lines/CyclePaths.svelte, src/lib/browse/layers/lines/Gradients.svelte, src/lib/browse/layers/lines/Trams.svelte, src/lib/browse/layers/points/Crossings.svelte, src/lib/browse/layers/points/CycleParking.svelte, src/lib/browse/layers/points/Education.svelte, src/lib/browse/layers/points/Hospitals.svelte, src/lib/browse/layers/points/RailwayStations.svelte, src/lib/browse/layers/points/SportsSpaces.svelte
9 easy layers regenerated, with no code changes in atip-data-prep. I've already updated the files on atip.uk, so the GH deployment will show new data. I compared all layers, no unexpected things missing, and I confirmed new known bus routes and cycle paths appear in Wirral and Bermondsey respectively. I didn't notice anything new in other layers, but I didn't really know where to look (and don't yet have a good geo-diffing workflow in place).
Pete, if these changes look good, please
1) Copy the 9 files to the GCS buckets. You can download the 9 files from http://atip.uk/layers/v1/cycle_paths.pmtiles and so on; let me know if I should just give you the 9 URLs
2) Update the manifests
=> Update OSM-based layers. #526

src/lib/browse/layers/areas/CombinedAuthorities.svelte, src/lib/browse/layers/areas/LocalAuthorityDistricts.svelte
Compare https://acteng.github.io/atip/ladsladslads_andcas/browse.html with the internal page. New CAs are clearly visible. I'm actually still hunting around to find the changes between January and May 2024 for LADs; Cumbria was already split by January.
Pete, you'll need to copy two new files to the GCS bucket: http://atip.uk/layers/v1/local_authority_districts.geojson and http://atip.uk/layers/v1/combined_authorities.geojson, and update manifest
=> Update LADs and CAs. #526

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/points/UserData.svelte, src/lib/browse/layers/points/UserDataPopup.svelte, src/lib/maplibre/zorder.ts
The browse tool is (by design) nice for quickly exploring different data, since has a few basemaps plugged in, streetview/measure tools, etc. To help one ad hoc analysis, I want those tools to check some custom data. This feels generally useful enough to make an ultra simple layer in browse. It could get much fancier later with ways to tune filtering and coloring (some ideas started in https://dabreegster.github.io/geojson-viewer/) but a simple start.
Demo https://acteng.github.io/atip/generic_browse/browse.html
=> Let the user display their own arbitrary GeoJSON file in browse

src/lib/sketch/About.svelte, src/lib/sketch/FileManagement.svelte, src/pages/ChooseArea.svelte, src/pages/LandingPage.svelte, src/pages/SketchSchemes.svelte
Made a decision to move about to landing page, we can reintroduce it elsewhere if we like.
=> Put about on landing page, remove ATIP word, fix small font thing

.github/workflows/playwright.yml, .gitignore, package-lock.json, package.json, playwright.config.js
Experimenting with https://ctrf.io/
=> Set up better test reporting

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/areas/RuralUrban.svelte, src/lib/maplibre/zorder.ts
Counterpart to https://github.com/acteng/atip-data-prep/pull/66
=> Add a RUC layer

src/lib/common/Geocoder.svelte
- speed up the animation
- prefer results close to the current map center
For #536
=> Improve geocoder:

src/lib/browse/layers/points/Crossings.svelte
Two fixes, both thanks to @rskedgell:
- Detect more parallel crossings (example by `#19.63/51.541493/-0.0113397`)
- Add an unknown signalised category (example by `#18.8/51.5464977/-0.0011429`)
Pete, please update using http://atip.uk/layers/v1/crossings.pmtiles, new md5sum is 281cfa9eeafd445d4de523d73b12575b
=> Adjust crossings layer, adding unknown signalised category. #480

package-lock.json, package.json
This fixed the `hybrid` style for me, and I don't notice any other changes. We could consider upgrading to [5](https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md), but it's just been out a week and svelte-maplibre might need some updates too.
Will do same for other repo.
=> Upgrade maplibre to fix #576

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/areas/Pollution.svelte
Broke everywhere due to DEFRA starting to enforce CORS. This layer has always had problems, #490, so our resolution should really be to track down the raw data, so we can process + host + display ourselves, like we do for road noise.
=> Disable the pollution layer. #490

src/lib/maplibre/highlight_roads.ts, src/lib/maplibre/styles.ts
I somehow missed that MapTiler has managed to adapt the super-detailed OSM "carto" style from the main page into vector tiles. I think it's a very useful basemap for some use cases on the browse page, so make it an option.
Demo https://acteng.github.io/atip/carto_basemap/browse.html?style=openstreetmap
=> Add OSM basemap style

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/areas/Pollution.svelte, src/lib/browse/layers/url.ts
…session can be resumed by default
Seems to  be working mostly okay except public transport layers don't work. will investigate but putting it up so you can see my approach and test it out
=> Adding querystring to local storage on browse page to store "layer session" 

src/lib/browse/layers/url.ts, src/lib/browse/schemes/LoadRemoteSchemeData.svelte, src/lib/browse/stores.ts, src/lib/common/MapLibreMap.svelte
More noticeable now that we save the query string!
To verify this works, go to `browse.html?disable_remote_schemes` initially, then "load latest scheme data", verify the URL changes. Go to `browse.html` with no params and verify schemes do load. (If you're testing locally, for the remote schemes to show up at all, follow the dev guide instructions for VITE_MIMIC_GCP_LOCALLY)
=> When the user initially uses ?disable_remote_schemes and then later loads the schemes, fix up the URL

.github/workflows/web.yml
Same problem and fix as inspectorate tools. Not sure what changed here, but `git branch -r` started listing this `HEAD -> main` thing and broke things. Just ignore it.
=> Fix GH actions

.github/workflows/deploy_private_dev.yml, .github/workflows/deploy_private_test.yml, .github/workflows/playwright.yml, .github/workflows/web.yml, backend/app_private_dev.yaml, backend/app_private_test.yaml, backend/app_public_dev.yaml, backend/app_public_prod.yaml
18 is deprecated and end-of-life in a few months of appengine. I've been running 22 on my local development machine for ages, so I don't expect anything to not work, but will let tests + the auto-deploy to test environments reveal any problems.
Also includes the #584 fix to have any hope of building
=> Upgrade node from 18 to 22

src/lib/maplibre/styles.ts
There's been a new version of this style for a while; the old is deprecated. I've preserved the URL query parameters.
=> Update to maptiler streets-v2 style

src/lib/browse/LayerControls.svelte, src/lib/browse/colors.ts, src/lib/browse/layers/lines/CycleRoutes.svelte, src/lib/maplibre/zorder.ts
Demo: https://acteng.github.io/atip/osm_routes/browse.html?cycle_routes=1#16.16/51.494749/-0.100203
I'm not sure why I never thought to include this. OSM has named cycle routes, modeled as relations. I think it's quite illustrative to look at these alongside the existing "cycle paths" layer, which should maybe be rephrased as "Cycle infrastructure". Compare the more semantic routes:
with the actual infrastructure making them:
Not sure it's visible easily in the screenshot, but Elliot's Row is an example where it's part of one logical route, but it's just a quiet residential street; there's no physical infrastructure there.
Note I'd love to let people click the routes and open in OSM, like https://www.openstreetmap.org/relation/11739129. But that'd require doing our own work to stitch …
=> Add a browse layer for existing OSM cycle routes

src/lib/browse/layers/lines/CycleRoutes.svelte
Needs https://github.com/acteng/atip-data-prep/pull/70 GCS updating there first
=> Include more detail about existing OSM cycle routes
