acteng/atip

app.js, areas.html, crossings.html, other.html, routes.html
- Rename lowercase scheme text
- Rename Titlecase words
Close #17
=> 23 interventions

app.js, scheme.html
Largely duplicate of #32 but with instructions more neatly in popup, not popping-up tho for some reason. I votethis way if we get it working so the app is neater, although a bit ugly buttons atm:
=> Instructions popup

App.svelte, ChooseArea.svelte, components/About.svelte, components/EntireScheme.svelte, index.html
1) Show what area is being hovered on the map
2) Clarify that the list contains both TAs and LADs
3) Add about button
https://user-images.githubusercontent.com/1664407/211301872-6f96ab80-edcb-411e-93e3-626c0f5e2f24.mp4
=> Improve homepage

components/EntireScheme.svelte
Good catch @Sparrow0hawk! This should fix
=> Don't clear authority and origin properties. #72

App.svelte, components/BaselayerSwitcher.svelte, components/Map.svelte
https://user-images.githubusercontent.com/1664407/227251357-2262a920-539a-4ab1-9102-225bd95a2bd4.mp4
See code comments for discussion points
=> Add a control to switch baselayers to satellite. #51

src/lib/AccordionItem.svelte, src/lib/EntireScheme.svelte, src/lib/Form.svelte, src/lib/InterventionList.svelte, src/lib/draw/AttributeMode.svelte, src/lib/draw/GeometryMode.svelte, src/lib/draw/HoverLayer.svelte, src/lib/draw/PointMode.svelte, src/lib/draw/PolygonMode.svelte, src/lib/draw/RouteMode.svelte, src/stores.ts, src/types.ts, tests/savefiles.spec.js
Along the way, create a few more stores to be more specific about map vs sidebar interactions.
https://user-images.githubusercontent.com/1664407/232451906-bf3fd349-c870-43fc-ae94-60b6cf6040bd.mp4
=> Replace Carbon's accordion with our own. #90

README.md, package-lock.json, package.json, src/App.svelte, src/ChooseArea.svelte, src/lib/About.svelte, src/lib/AccordionItem.svelte, src/lib/ExternalLink.svelte, src/lib/Form.svelte, src/lib/Instructions.svelte, src/lib/Modal.svelte
This PR finishes removing the Carbon component system, which was a hasty original choice. #90 
In the short term, this gives us much easier full control over everything. Longer term, if we need to adopt the govuk frontend styles, this frees us up to do it.
Some style changes visible below. Very happy to make any changes.
https://user-images.githubusercontent.com/1664407/232755298-db7dddf3-3138-49eb-9aaa-ebcb4ba75e7c.mp4
=> Eliminate Carbon

package-lock.json, package.json, src/ChooseArea.svelte, src/lib/BoundaryLayer.svelte, src/lib/ZoomOutMap.svelte, src/lib/draw/AttributeMode.svelte, src/lib/draw/GeometryMode.svelte, src/lib/draw/InterventionLayer.svelte, src/lib/draw/PointMode.svelte, src/lib/draw/PolygonMode.svelte, src/lib/draw/RouteMode.svelte, src/lib/draw/SplitRouteMode.svelte, src/lib/draw/Toolbox.svelte, src/lib/draw/point_tool.ts, src/lib/draw/polygon_tool.ts, src/lib/draw/types.ts, src/maplibre_helpers.ts
We have no errors with the current `tsconfig.json`, but adding `strict: true` yields around 200 problems. This PR whittles it down to 38. #89 
No behavioral changes
=> Use TypeScript more

src/App.svelte, src/ChooseArea.svelte, src/lib/EntireScheme.svelte, src/lib/Form.svelte, src/lib/draw/AttributeMode.svelte, src/lib/draw/HoverLayer.svelte, src/lib/draw/point_tool.ts, src/lib/draw/polygon_tool.ts, src/maplibre_helpers.ts
Home-stretch! The last few problems are harder to deal with, though. #89
No behavioral changes.
=> More TS fixes. Down to 5 strict errors!

src/App.svelte
As per comments here https://github.com/acteng/atip/pull/145#issuecomment-1533573887 I think schema is a more useful word than Design here, even though it does affect the UI design.
=> Update App.svelte: Design -> Schema

src/lib/EntireScheme.svelte, tests/modes.spec.js
The test added explains how to repro; I don't need to repeat it here. ;) I noticed it due to this console error:
Attribute mode then acts strange after
=> Fix bug with clear-all

README.md
FYI @robinlovelace-ate and @Sparrow0hawk
=> How to deploy ATIP outside UK

src/lib/EntireScheme.svelte
Quite straightforward! Just add `geojsonUrl=xyz`
I tried to add a test for this:
```
test("loading from URL", async ({ page }) => {
await page.goto(
"/scheme.html?authority=Isle of Wight&geojsonUrl=https://gist.github.com/dabreegster/e3aed0cffc59e8ac47e2e303641bac
39/raw/b03d1afc64d4d998b7b564671f257022b012031b/Isle%2520of%2520Wight_Holiday.txt"
);
await page.getByRole("button", { name: "1) Hike part 1" }).click();
});
```
But hit CORS errors; we can't fetch from Github gists like this. Not sure how to host a file locally with Playwright. If anyone's got another idea for a stable-over-time URL to stash a tiny txt file, we could use it. (Is it worth putting in the S3 bucket?)
=> Load from a URL specified in query params. #172

.devcontainer/devcontainer.json, docs/developer_guide.md
Add a docker dev container config, and update readme to explain how to use in VSCode
=> Add dev container

src/lib/draw/StreetViewMode.svelte, src/lib/draw/route/RouteControls.svelte, src/stores.ts, src/types.ts, tsconfig.json
Not many for now, but this could be useful over time
=> Store some user settings in local storage

scheme.html, src/lib/common/Layout.svelte, src/pages/App.svelte
No behavioral diff that I can see, and less code!
=> Clean up old CSS hacks

package-lock.json, package.json, tsconfig.json
@Pete-Y-CS, could you try this branch, do `npm i`, then `npm run check`, and paste what errors it shows please?
=> Make sure node TS types are configured

index.html, scheme.html, src/lib/sidebar/About.svelte, src/lib/sidebar/EntireScheme.svelte, src/pages/App.svelte, src/pages/ChooseArea.svelte, tests/homepage.spec.ts
For discussion tomorrow. I think the launch checklist should be:
This PR updates a bunch of text to say v2 instead of v1. The significant change is to disable the v2 schema from the dropdown, since it's not ready for use by anyone.
=> Release v2

browse.html, src/lib/common/MapTooltips.svelte, src/lib/draw/InterventionLayer.svelte, src/lib/layers/SpeedLimits.svelte, src/pages/BrowseSchemes.svelte, vite.config.ts
Start #173. This page is meant for inspections, or anyone with a bunch of ATIP schemes. Intended functionality:
- see all ATIPs on a map, and quickly hover on stuff to see details
- filter/search schemes by free-form text
- open the main ATIP edit mode with one of the schemes
- see basic summary stats for all the ATIPs
This is at the point where it's demoable to inspections to get feedback.
=> Browse schemes page

docs/developer_guide.md
Pete is the newest to go through this process, so you may have opinions here!
=> Add links to learning guides for the tech stack. #221

src/lib/Legend.svelte, src/lib/common/Modal.svelte, src/lib/draw/AttributeMode.svelte, src/lib/draw/GeometryMode.svelte, src/lib/draw/StreetViewMode.svelte, src/lib/draw/route/SplitRouteMode.svelte, src/lib/layers/lane_details/Layer.svelte, tests/modes.spec.ts, tests/savefiles.spec.ts, tsconfig.json
No idea why this option isn't on by default in tsconfig, it's super handy!
=> Fix unused imports and variables

src/lib/common/ConfirmationModal.svelte, src/lib/common/FileInput.svelte, src/lib/common/Modal.svelte, src/lib/draw/point/point_tool.ts, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/route/route_tool.ts, src/lib/sidebar/EntireScheme.svelte, src/stores.ts, tests/modes.spec.ts, tests/savefiles.spec.ts, tests/settings.spec.ts, tests/shared.ts
…files and clearing all
This is a new version of:
https://github.com/acteng/atip/pull/196
The old work for that, for now, is kept at the branch: `state-changing-bugs-142-legacy` so I can refer to it if there's stuff I want to reuse.
=> State changing bugs: disable things when editing 142

src/pages/ChooseArea.svelte
on
This is a small improvement in functionality when initially picking an area. When we add MCAs or other divisions, this will let users slice things how they like.
https://github.com/acteng/atip/assets/1664407/765577aa-ff1c-42d1-acc0-841be07ca77f
Thoughts on showing the hovered name underlined in the sidebar? Would regular tooltips on the map be easier, to not jump attention around?
And this change reveals that our LAD data in this repo is incomplete, see #264
=> Let users show LADs or TAs on the first page, and show the area hovered

docs/developer_guide.md
=> Update developer guide to highlight a couple of requirements

docs/schema.md
I added https://github.com/acteng/schema/blob/main/article.md in early April, but didn't get much feedback at the time. This is a slightly updated copy, moved here for visibility and to re-open some questions, since we're looking at this actively again. Please comment/discuss!
=> Move schema design doc into docs

docs/backend.md
This is more like a set of questions we need to start exploring, rather than a design. Happy to try other formats for this (like Google Docs with comments), but I think it could be helpful to document the architectural decisions we make as the project evolves.
There are _tons_ of questions raised, please comment!
=> Start a design doc for an ATIP backend + database

src/pages/ChooseArea.svelte
Not sure why we didn't do this originally, but it's much easier than glancing over to the side to the see the name.
https://github.com/acteng/atip/assets/1664407/1f1fcc3e-25f1-443d-a567-2030ddea1229
=> Use tooltips to show the area name on the homepage

src/lib/browse/InterventionColorSelector.svelte, src/lib/draw/route/route_tool.ts, src/lib/layers/lane_details/IntersectionMarkings.svelte, src/lib/layers/lane_details/IntersectionPolygons.svelte, src/lib/layers/lane_details/LaneMarkings.svelte, src/lib/layers/lane_details/LanePolygons.svelte, src/maplibre_helpers.ts, src/pages/BrowseSchemes.svelte, src/schemas.ts
Not fully finished reviewing the existing changes but here are some cosmetic changes that I _think_ would make it less confusing to me/other newcomers
=> Coloring changes

src/lib/browse/LocalPlanningAuthoritiesLayerControl.svelte, src/lib/browse/colors.ts, src/maplibre_helpers.ts, src/pages/BrowseSchemes.svelte
https://github.com/acteng/atip/assets/1664407/d4727afa-e745-46ba-b23c-780819cbb840
Just something simple to start with
=> Add LPA boundaries. #285

src/lib/browse/LayerControls.svelte, src/lib/common/StreetViewController.svelte, src/lib/draw/StreetViewMode.svelte, src/lib/maplibre/layer_helper.ts, src/lib/maplibre/layer_helper_utils.ts
1) Include paths in the highlighted layer, since it's likely of interest
2) Make the escape key also work in browse mode
3) Fix a bug in the scheme sketching mode where clicking would cause the streetview reaction twice
=> Streetview fixes

backend/README.md, backend/app.yaml, backend/package-lock.json, backend/package.json, backend/server.js, package-lock.json, package.json, src/lib/browse/LoggedIn.svelte, src/pages/BrowseSchemes.svelte
Pretty straightforward to follow https://cloud.google.com/iap/docs/signed-headers-howto
=> Verify IAP headers, and figure out who's logged in

src/lib/browse/layers/CrossingsLayerControl.svelte, src/lib/browse/layers/RailwayStationsLayerControl.svelte
Some of my PR comments might not've shown up? Few style tweaks
=> Feedback for #343

src/lib/browse/LayerControls.svelte, src/lib/browse/colors.ts, src/lib/browse/layers/CyclePathsLayerControl.svelte, src/lib/browse/layers/PctLayerControl.svelte, src/lib/maplibre/utils.ts
Demo: https://acteng.github.io/atip/pct/browse.html (should be deployed by ~12:45)
=> Add a PCT layer. #337

src/lib/browse/AppVersion.svelte, src/lib/common/Alpha.svelte, src/lib/common/LoggedIn.svelte, src/lib/common/index.ts
Demos:
https://acteng.github.io/atip/alpha/browse.html
https://acteng.github.io/atip/alpha/critical_entry.html
https://acteng.github.io/atip/alpha/scheme.html?authority=Adur
=> Add an alpha banner to most pages

src/lib/common/index.ts, src/pages/ChooseArea.svelte, src/pages/SketchSchemes.svelte
When someone visits https://acteng.github.io/atip/pipeline/scheme.html, set the default URL parameter appropriately. We only want this for this branch right now
=> Default to the pipeline schema on that branch

package-lock.json, package.json, src/lib/draw/route/GeocoderControls.svelte, src/lib/draw/route/GeocoderLayer.svelte, src/lib/draw/route/RouteControls.svelte, src/lib/draw/route/route_tool.ts, src/lib/draw/route/stores.ts, src/pages/SketchSchemes.svelte
https://github.com/acteng/atip/assets/1664407/1ebb8c54-2c3a-4718-93fc-3c9a951d1195
Demo at https://acteng.github.io/atip/route_snapper_geocoder/scheme.html?authority=LAD_Adur   (in a few minutes)
#389 
The UX isn't perfect, but feels like a usable start to me
=> Let waypoints be added to the route snapper using the geocoder

src/lib/draw/polygon/PolygonControls.svelte, src/lib/draw/polygon/polygon_tool.ts, src/lib/draw/polygon/stores.ts
#44 
https://acteng.github.io/atip/undo_polygon/scheme.html?authority=LAD_Adur
https://github.com/acteng/atip/assets/1664407/49191fb6-2cbb-431e-bd03-ef5bb1201e8c
=> Undo in the freehand polygon tool

src/lib/forms/PipelineForm.svelte, src/lib/sidebar/GenericSchemeForm.svelte, src/lib/sidebar/ListMode.svelte, src/lib/sidebar/PipelineSchemeForm.svelte, src/lib/sidebar/scheme_data.ts, src/pages/ChooseArea.svelte, src/pages/SketchSchemes.svelte, src/stores.ts, tests/pipeline.spec.ts, tests/shared.ts
1) Add a test checking that the warnings for missing data behave as expected, and that data gets saved and restored after a refresh
2) Simplify how the pipeline backfill logic happens
3) Fix an existing bug where scheme details aren't actually saved if you close the modal by clicking the map!
=> Be very careful with pipeline scheme data

src/lib/forms/PipelineForm.svelte, src/lib/sidebar/PipelineSchemeForm.svelte, src/lib/sidebar/scheme_data.ts, src/types.ts, tests/pipeline.spec.ts
#389 
This matches the data spec doc now
=> Change pipeline budget fields and make accuracy required

src/lib/browse/Filters.svelte, src/lib/browse/InterventionLayer.svelte, src/lib/browse/InterventionPopup.svelte, src/lib/browse/SchemeCard.svelte, src/lib/browse/stores.ts, src/pages/BrowseSchemes.svelte
https://acteng.github.io/atip/browse_store_popups/browse.html
Only show name on hover. If you click, the popup is sticky and you get more info
https://github.com/acteng/atip/assets/1664407/fd69dfc3-4138-4de7-912d-0a642eea88d2
=> Make browse page popups nicer

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/lines/PavementWidths.svelte, src/lib/maplibre/zorder.ts, src/lib/sidebar/PipelineSchemeForm.svelte, src/types.ts
Similar to the road width layer, but with less data outside of cities (because there's no pavement). We need to add the file to the GCS bucket first for this to work.
=> Add OS pavement width layer. #432

package-lock.json, package.json
https://github.com/dimfeld/svelte-maplibre/pull/123 is particularly helpful for cases where we destroy/recreate a component with hovering or popups
=> Update svelte-maplibre to get popup fixes

src/lib/maplibre/utils.ts
650-850ms down to 5-10ms. No behavioral change; I tested sketch and browse, showing/hiding/editing stuff.
=> Speed up addLineStringEndpoints by 10x. #454

src/lib/browse/Filters.svelte
=> Button to reset all filters. #463

src/lib/browse/LayerControls.svelte, src/lib/browse/colors.ts, src/lib/browse/layers/lines/Trams.svelte, src/lib/browse/layers/points/BusStops.svelte, src/lib/maplibre/zorder.ts
Demo at https://acteng.github.io/atip/pt_layers/browse.html
Need to upload 2 new pmtiles to both GCP environments. They're in S3 already.
=> Tram and bus stop frequency layer

src/lib/browse/LayerControls.svelte, src/lib/browse/layers/areas/Pollution.svelte, src/lib/browse/layers/areas/RoadNoise.svelte, src/lib/maplibre/zorder.ts
Demo at https://acteng.github.io/atip/road_noise/browse.html, "Other  > Road noise". Compare to http://www.extrium.co.uk/noiseviewer.html.
=> Add road noise layer. #491

src/lib/browse/Filters.svelte, src/types.ts
A quick and dirty fix for filtering by sketch source: maybe useful, certainly useful to have a branch which modelling users can see the delineation!
=> Add sketch source to browse page

src/lib/browse/layers/lines/PavementWidths.svelte
Needs https://github.com/acteng/atip-data-prep/pull/60 to be uploaded first
=> Show both sides of the road for pavement width

package-lock.json, src/lib/browse/layers/lines/PCT.svelte, src/lib/browse/layers/lines/RoadSpeeds.svelte, src/lib/sketch/FormV1.svelte, src/lib/sketch/pipeline/PipelineForm.svelte, src/lib/sketch/pipeline/PipelineSchemeForm.svelte, src/lib/sketch/pipeline/TimingForm.svelte, src/pages/ChooseArea.svelte
making radio labels consistently bolded
Just making a PR to trigger playwright tests (to make sure the selectors work with the Radio changes)
=> Update ss-lib, fixing excess whitespace beneath sketch toolbox and also

backend/server.js
=> Serve route snapper files through the GAE proxy

src/lib/browse/layers/points/Stats19.svelte
Please upload http://atip.uk/layers/v1/stats19.pmtiles to the test bucket and update manifest
=> Update stats19 layer with 2023. #526

package-lock.json, package.json, src/lib/sketch/GenericSchemeForm.svelte, src/lib/sketch/pipeline/PipelineForm.svelte, src/lib/sketch/pipeline/PipelineSchemeForm.svelte, tests/pipeline.spec.ts
Counterpart to https://github.com/acteng/scheme-sketcher-lib/pull/6
=> Redesign scheme management

src/lib/browse/LayerControls.svelte, src/lib/browse/colors.ts, src/lib/browse/layers/lines/RightsOfWay.svelte, src/lib/maplibre/zorder.ts
We'll need to upload the pmtiles generated in atip-data-prep to the GCS bucket. TBD how to keep this data up-to-date reasonably.
Demo:
=> Rights of way layer

accessibility.html, browse.html, choose_area.html, files.html, index.html, local_storage.html, scheme.html, src/pages/AccessibilityStatement.svelte, src/pages/LandingPage.svelte
Will finish scrubbing ATIP in another PR
=> Add accessibility statement and begin to scrub ATIP from the site

package-lock.json, src/lib/browse/layers/points/UserData.svelte, src/lib/maplibre/zorder.ts, src/pages/LandingPage.svelte, src/pages/SketchSchemes.svelte, tests/edits.spec.ts, tests/modes.spec.ts
Main PR in https://github.com/acteng/scheme-sketcher-lib/pull/8. Opening this PR to trigger tests.
=> Use new route/area snapper UI

src/lib/common/Header.svelte, src/lib/common/index.ts
may want some styling changes, and currently testing on public beta env but here's a WIP
=> Add a warning if you're in the public beta dev/test env

src/lib/browse/schemes/SchemesLayer.svelte
=> Option to download all local schemes for use in other GIS

package-lock.json
=> Pull in dep for draw tool hotkeys

src/pages/LandingPage.svelte, src/pages/SketchSchemes.svelte
Quickly adding a couple of links to the site for the tutorial
=> Add the links to the tutorial pages

src/lib/browse/schemes/SchemesLayer.svelte, src/lib/browse/schemes/colors.ts
With this I can upload a new version of all_schemes_output.geojson.gz to the internal version of the browse page
=> Handle atf5

.github/workflows/deploy_public_prod.yml
=> create public prod workflow
